version: "3.9"
services:
  mongodb:
    image: mongo:6.0
    container_name: movie-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: moviedb
    volumes:
      - mongo_data:/data/db

  movie-api:
    build: .
    container_name: movie-api
    ports:
      - "${SERVER_PORT:-8080}:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SERVER_PORT: ${SERVER_PORT}
#      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    restart: always

volumes:
  mongo_data:
