#server:
#  port: ${SERVER_PORT:8080}
#
#spring:
#  application:
#    name: Movie Management API
#
#  data:
#    mongodb:
#      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/moviedb}
#
#springdoc:
#  api-docs:
#    enabled: true
#    path: /api-docs
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
